### ISSUE TITLE
New checks for organization and individual information in CATALOG.XML

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#10]
If discovery metadata attributes of type CI_Organisation and CI_Individual are populated their content must conform to Tables 17-2 and 17-3, pages 31-32.

Table and page numbers are as in Ed. 5.0.0.

This may result in more than one check, going by the tables.

Applies to S100_DatasetDiscoveryMetadata.{producingAgency, metadataPointOfContact}

**Comment by rmalyankar** [comment]
Proposed formulation of checks:

| Check ID | Description | Classification| S-100 Part | S-100 clause|
|--------|--------|--------|--------|--------|
| ?  | If CI_Individual is present then at least one of CI_Individual.name,  CI_Individual.positionName, or CI_Individual.partyIdentifier must be populated | W | 17 | 4.5 Table 17-2 |
| ? | If CI_Organisation is present then at least one of CI_Organisation.name or CI_Organisation.positionName must be populated | W | 17 | 4.5 Table 17-3 |
| ? | If CI_Organisation is present and neither of CI_Organisation.name and CI_Organisation.positionName is populated then CI_Organisation.partyIdentifier must be populated  | W | 17 | 4.5 Table 17-3 |
| ? | If CI_Individual or CI_Organisation is present then contact information within it must be populated with at least one of phone, address, onlineResource, or contactInstructions | W | 17 | 4.5 Tables 17-2, 17-3, Note 2 |


"populated" means the element must be present and its content cannot be empty or blank (cannot consist only of whitespace). (If it has only element content the non-blank requirement applies to the tree under it, i.e., the totality of its sub-elements, sub-sub-elements, etc.)
The redundancy of the partyIdentifier check for CI_Organisation is noted and should be clarified in S-100.

**Comment by LizHahessy** [comment]
Agreed at VTC 8 to include the new checks, but will increase the Classification to an Error as it is an inconsistency with the S-100 Standards. 
Once included, this Issue will be closed.

**Comment by rmalyankar** [comment]
Still to do? Should be reopened or new issue created until addition is confirmed.
