### ISSUE TITLE
Proposed checks for locale consistency between resource and discovery metadata block

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#11]
Checks for S100_DatasetDiscoveryMetadata and S100_CatalogueDiscoveryMetadata:
1. If a dataset or catalog uses a language or languages other than (or in addition to) English, every language in the dataset/catalog must be indicated in defaultLocale/otherLocale attributes in the corresponding discovery metadata block. 
2. If English is one of the languages used in a dataset or catalog, it must be encoded in defaultLocale.

Check for S100_SupportFileDiscoveryMetadata:
1. If a support file is in a language other than English, the language must be encoded in defaultLocale in the corresponding S100_SupportFileDiscoveryMetadata block.

Check for support file content:
1. A support file that contains informative text intended for display to end-users must use only one language for all such text.

**Comment by rmalyankar** [comment]
> 1. Why? I don't understand why this is useful for dataset/catalog discovery.
...

* Where in the dataset is this information encoded? What if the dataset is encrypted? Requires a paid license?
* Where is the requirement that the catalog (which catalog?) is always required to be in English?
* If locale information is not needed I suggest submitting a proposal to remove those attributes from the respective metadata classes.

> ...it should only be required to encode a defaultLocale if it is not English.

The check ensures that English is not encoded in an _otherLocale_ instead of _defaultLocale_ when there are multiple languages.

**Comment by LizHahessy** [comment]
Agreed at VTC 3 04/09/23 that a paper would be submitted to S-100WG 8.  Review after meeting.
http://iho-portal.bluemap.kr/share/files/387

**Comment by LizHahessy** [comment]
Paper was withdrawn at S-100WG8 following discussion.  Recommend close issue.

**Comment by LizHahessy** [comment]
Discussed at VTC 8 and agreed to close Issue.
