### ISSUE TITLE
S-101: Require `valueOfSounding` or `defaultClearanceDepth`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-100-Validation-Checks#12]
Require that one of `valueOfSounding` or `defaultClearanceDepth` must be encoded (can't both be unknown) for:
* `Wreck`
* `Obstruction`
* `UnderwaterAwashRock`

https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/10#issuecomment-1667844996

**Comment by LizHahessy** [comment]
Agreed at S-100 Validation VTC 3 that this needs to move to S-101 Validation.

**Comment by DavidGrant-NIWC** [comment]
Issue has been moved to the (newly created) S-101 Validation repo: [S-101 Issue](https://github.com/iho-ohi/S-101-Validation/issues/1)
