### ISSUE TITLE
Part 5 checks - S100_Dev0065

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#17]
> S100_Dev0065		A Feature Catalogue shall be defined for each Product Specification

> S100_Dev0067		A Feature Catalogue shall be available in electronic form for any set of geographic data that contains features

There is no feature catalogue for S-98 Data Product Interoperability. Also, 0065 is included in S100_Dev0067. Suggest deletion of 0065.

**Comment by LizHahessy** [comment]
At VTC 8 it was agreed that this checks should be moved to S-164 repository.
This issue has been transferred to S-164 repository https://github.com/iho-ohi/S-164-Sub-Group/issues/85
Checks have been set to 'strikethrough' and this issue will be closed.
