### ISSUE TITLE
Part 5 checks - S100_Dev0066, S100_Dev0068, S100_Dev0071, S100_Dev0073, S100_Dev0076

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#18]
> S100_Dev0066		Definitions of features and attributes are drawn from a Feature Concept Dictionary
> S100_Dev0068		Feature catalogue is based on the ISO 19110 standard with extensions to features types (information types and complex attributes)
> S100_Dev0071		Attributes cannot be shared between different instances
> S100_Dev0073		Each association has exactly two roles, either or both may be default.
> S100_Dev0076		Each Feature Association uses two roles that define the directed use of the relationship. Either or both may be default.

I think the checks above are descriptive rather than prescriptive and can be removed. Also, 0071 applies to instances and not feature catalogues.

**Comment by LizHahessy** [comment]
Agreed at VTC 8 that these checks can be removed.  Set to 'strikethrough' 
Issue closed.
