### ISSUE TITLE
Conformance of XML FC to schema

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#19]
Noted that there does not seem to be an explicit requirement in Part 5 that the XML feature catalogue for a particular edition of an S-100 prroduct specification conform to the IHO-provided XML schema for the S-100 edition on which the product specification is based. If we can institute such a check the following would be included in a requirement for conformance to the the XML schema:

> S100_Dev0070		Each type cannot be derived from more than one super-type
> S100_Dev0072		All simple attribute values are value types from the list in Part 2a-4.2.9

**Comment by LizHahessy** [comment]
Agreed at VTC 8 to remove both checks as there is no explict requirement in Part 5.  Checks both set to 'strikethrough'.
Discussed whether it was necessary to give feedback to S-100 WG, it was agreed that it was not necessary.
Issue closed.
