### ISSUE TITLE
Part 5 checks  - S100_Dev0074, S100_Dev0075

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#20]
> S100_Dev0074		The documentation of Application Schemas must specify the role used for default names.
> S100_Dev0075		Each role shall have an unambiguous name.

I don't see how 0074 can be enforced by code, at least not without significant work on making documentation machine-processable. 

Given that some product specifications use the same role name in different associations (which is not a practice I would recommend) 0075 might also be difficult to enforce, especially in code.

**Comment by LizHahessy** [comment]
Discussed at VTC 8 and agreed that these were S-99 Annex A issues and should be removed from S-100 Validation.  Jeff made a note to ensure these points are covered in S-99 Annex A.
Set to 'strikethrough' and issue closed.
