### ISSUE TITLE
Part 7 checks Dev0081, Dev0087 are product-specific

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#21]
> S100_Dev0081		The blendedParabolic interpolation should not be used where the precise location of the resultant curve is important

This is guidance for Product Specification authors rather than a check, whether the precise location is important would be decided at the Product Specification level, so this is actually a requirement for the Product Specification to specify which interpolation type is allowed. While we can expect the precise location to be important for geographic features, that doesn't necessarily apply to meteorological information.

> S100_Dev0087		Individual Product Specifications may constrain the interpolation types allowed for spatial attributes

This too would be decided at the Product Specification level.

Recommend removing 0081 and 0087 from the S-100-level checks.

**Comment by LizHahessy** [comment]
Agreed at VTC 8 that these checks were product specific and that should be removed from S-100 Validation.
Checks set to 'strikethrough' and Issue closed.
