### ISSUE TITLE
Part 7 check S100_Dev0088

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#22]
> S100_Dev0088		GM_Primitives are part of at least one GM_Aggregate

The cited S-100 clause 7-4.2.11.1 does say that but it is inaccurate and not supported by the UML diagram in Figure 7-3; nor have I been able to find the ISO 19107 clause it cites (ISO 19107 clause 8.10.1). ISO 19107:2003 describes GM_Primitive in clause 6.3.10 but that does not contain this statement from S-100 7-4.2.11.1.

The S-100 statement appears to be a misunderstanding or typographical error.  Recommend removal of this validation check.

**Comment by LizHahessy** [comment]
S-100 Change Proposal Form submitted to S-100 WG9 Nov 2024 to remove statement in Part 7 at the next version of S-100.

**Comment by LizHahessy** [comment]
4.11 was submitted to S-100 WG9 as a proposal to remove the text “All geometric primitives (GM_Primitive) must be part of at least one GM_Aggregate (see ISO 19107 clause 8.10.1).“ from Part 7 4.2.11.1.
Approved at meeting.
