### ISSUE TITLE
Checks for constraints and conformance of attribute value to FC constraints, Part 5, Part 10a

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#28]
> S100_Dev0072		All simple attribute values are value types from the list in Part 2a-4.2.9		5	4.2.3.3

More checks are needed. Ref. https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/104 for related comments.

| Check ID| Description	| Classification	| S-100 Part| S-100 clause|
|--------|--------|--------|--------|--------|
| ? | If constraints are provided in the feature catalogue definition of a simple attribute, the constraints shall be compatible with the datatype of the attribute. | E | 5 |  |
| | | | | |
| ? | The value of a simple attribute is consistent with its value domain as defined in the FC | E | ? |  |
| | | | | |
| ? | Placeholder for checks corresponding to 10a-5.1.4 (Encoding of attribute values) | E | 10a | 10a-5.1.4 |

The second check is a check on the dataset, and would be common to all data formats; not clear at the moment how that kind of thing should be attributed in the list of validation checks.

**Comment by FrankHippmann** [comment]
The second check would belong in the set checks that verifies a dataset's conformance to the constraints defined by the FC, e.g., see S100_Dev00161 - S100_Dev0168.  This is more related to Part 5, and not Part 10a.

**Comment by rmalyankar** [comment]
Didn't find them in the _4 spreadsheet or GitHub README, should be reopened or new issue created until addition is confirmed.
