### ISSUE TITLE
Draft S-100 and S-101 Validation Checks at 20220106

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-100-Validation-Checks#3]
This Excel Spreadsheet contains the draft prepared in May 2021 by this group. It contains;

An initial set of S-100 checks tailored for S-101 (Part 1)

An intiial set of S-101 checks (Part 2)

A cross reference to S-58 6.1.0 checks (Part 3)

A tab detailing current limitations and summary totals of checks (Part 4)

2 proposals that are now superseded by the use of Github (issues 1 and 2)

[S-101 Validation Checks Draft 0.2 20220106.xlsx](https://github.com/iho-ohi/S-100-Validation-Checks/files/7829187/S-101.Validation.Checks.Draft.0.2.20220106.xlsx)

**Comment by LizHahessy** [comment]
Part 1 checks have been adopted by S100 Validation and have been incorporated into the Validation Checks - closing Issue
