### ISSUE TITLE
Proposed Change to S-101 Check S-101_A_048

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-100-Validation-Checks#4]
Currently check S-101_A_048 covers "Mandatory attribute has not been populated with a value." and its severity is Error. It is proposed that the feature and attribute combinations should be reviewed and covered either the severity be changed to Critical or the check be split into checks with Critical and Error severities depending on the scenario. 

The following categorization is proposed based on the rationale that this should be Critical where portrayal is affected and an Error where it is not. This list does need updating to reflect S-101 1.0.2.

ARCSLN: NATION; ERROR
ASLXIS: NATION; ERROR
CONZNE: NATION; ERROR 
COSARE: NATION; ERROR
CTNARE: INFORM or 
TXTDSC;  ERROR
CUSZNE: NATION; ERROR
DEPARE: DRVAL1 and 
DRVAL2; CRITICAL
DEPCNT: VALDCO; CRITICAL 
DRGARE: DRVAL1; CRITICAL  
DWRTPT: ORIENT; ERROR
DWRTCL: ORIENT; ERROR
EXEZNE: NATION; ERROR
FSHZNE: NATION; ERROR
LNDELV: ELEVAT; CRITICAL
M_COVR: CATCOV; 
M_CSCL: CSCALE; CRITICAL
M_NSYS: MARSYS or 
ORIENT; CRITICAL
M_QUAL: CATZOC; CRITICAL
M_SDAT: VERDAT; ERROR
M_VDAT: VERDAT; ERROR
MAGVAR: VALMAG; CRITICAL
NEWOBJ: CLSDEF and 
CLSNAM; CRITICAL N/A for S-101
RCTLPT: ORIENT; ERROR
RESARE: CATREA or 
RESTRN; CRITICAL
STSLNE: NATION; ERROR
SWPARE: DRVAL1;  CRITICAL  
TESARE: NATION;  ERROR
TS_PAD: TS_TSP. ERROR

**Comment by KlasOstergren-SMA** [comment]
Issue have been transfered to S-101 validation repository
https://github.com/iho-ohi/S-101-Validation/issues/2
