### ISSUE TITLE
S100_050, S100_061, S100_064

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100-Validation-Checks#8]
The following are rules for production, interpretation, or dataset management, rather than validation checks - they cannot be applied to check anything, instead they specify "what to do" rather "what the subject(*) must or must not have".

> S100_050	When a datasets is cancelled it must be removed from the system
> S100_061	The start and end instants of [t]he interval calculated by combining userDefinedMaintenanceFrequency with the issue date/time must be interpreted according to Part 3 Clause 3-8
> S100_064	If both userDefinedMaintenanceFrequency and the maintenanceDate are encoded in the same discovery metadata block, the maintenanceDate supersede the userDefinedMaintenanceFrequency

_(*) dataset for 050, metadata discovery block for 061 and 064_

Check 050 specifies the state of the end-user system after ingesting/integrating a cancellation; 061 and 064 specify how the end-user application must interpret certain elements in discovery metadata.
They might perhaps be rewritten as requiring verification that the producer's intent is consistent with the mandated action or interpretations, but was that the intent in including them or does it stretch the meaning of "validation check" further than we want?

**Comment by LizHahessy** [comment]
Agreed at VTC 3 to move to S-164
